<?php


function actions($input=null){
    $output =[
        ACTION_DASHBOARD_VIEW=>'Dashboard View',
        ACTION_USER_VIEW => 'User View',
        ACTION_USER_ADD => 'User Add',
        ACTION_USER_EDIT => 'User Edit',
        ACTION_USER_DELETE =>'User Delete',
        ACTION_ROLE_VIEW=>'Role View',
        ACTION_ROLE_ADD=>'Role Add',
        ACTION_ROLE_EDIT=>'Role Edit',
        ACTION_ROLE_DELETE=>'Role Delete',
         ACTION_LOT_VIEW => 'Lot View',
         ACTION_LOT_ADD => 'Lot Add',
         ACTION_LOT_EDIT => 'Lot Edit',
         ACTION_LOT_DELETE => 'Lot Delete',
         ACTION_PRODUCT_VIEW => 'Product View',
         ACTION_PRODUCT_ADD => 'Product Add',
         ACTION_PRODUCT_EDIT => 'Product Edit',
         ACTION_PRODUCT_DELETE => 'Product Delete',
         ACTION_SUPPLIER_VIEW => 'Supplier View',
         ACTION_SUPPLIER_ADD => 'Supplier Add',
         ACTION_SUPPLIER_EDIT => 'Supplier Edit',
         ACTION_SUPPLIER_DELETE => 'Supplier Delete',
         ACTION_BRAND_VIEW => 'Brand View',
         ACTION_BRAND_ADD => 'Brand Add',
         ACTION_BRAND_EDIT => 'Brand Edit',
         ACTION_BRAND_DELETE => 'Brand Delete',
         ACTION_CATEGORY_VIEW => 'Category View',
         ACTION_CATEGORY_ADD => 'Category Add',
         ACTION_CATEGORY_EDIT => 'Category Edit',
         ACTION_CATEGORY_DELETE => 'Category Delete',
         ACTION_WAREHOUSE_VIEW => 'Warehouse View',
         ACTION_WAREHOUSE_ADD => 'Warehouse Add',
         ACTION_WAREHOUSE_EDIT => 'Warehouse Edit',
         ACTION_WAREHOUSE_DELETE => 'Warehouse Delete',
        ACTION_CUPON_VIEW => 'Cupon View',
        ACTION_CUPON_ADD => 'Cupon Add',
        ACTION_CUPON_EDIT => 'Cupon Edit',
        ACTION_CUPON_DELETE => 'Cupon Delete',
        ACTION_SELL_PRODUCT => 'Sell Product',
        ACTION_CSV_UPLOAD => 'Csv Upload',
        ACTION_EXCEL_UPLOAD => 'Excel Upload',
        ACTION_SETTINGS => 'Settings',
        ACTION_REPORT => 'Report',
    ];
    if(is_null($input)){
        return $output;
    }else{
        return $output[$input];
    }
}

// product type
function productType($input=null){

    $output = [
        ['id'=>PRODUCT_TYPE_PHYSICAL,'title'=>'Physical'],
        ['id'=>PRODUCT_TYPE_DOWNLOADABLE,'title'=>'Downloadable']
    ];
    if(is_null($input)){
        return $output;
    }
}

function discountType($input=null){
    $output=[
        PRODUCT_DISCOUNT_TYPE_FLAT=>['id'=>PRODUCT_DISCOUNT_TYPE_FLAT,'title'=>'Flat'],
        PRODUCT_DISCOUNT_TYPE_RATIONAL=>['id'=>PRODUCT_DISCOUNT_TYPE_RATIONAL,'title'=>'Percentage']
    ];
    if(is_null($input)){
        return $output;
    }else{
        return $output[$input];
    }
}

function months($input=null){
    $output=[
        1=>'January',
        2=>'February',
        3=>'March',
        4=>'April',
        5=>'May',
        6=>'June',
        7=>'July',
        8=>'August',
        9=>'September',
        10=>'October',
        11=>'November',
        12=>'December',
    ];
    if(is_null($input)){
        return $output;
    }else{
        return $output[$input];
    }
}

//country list
function country($input=null){
    $output = [
        'af' => 'Afghanistan',
        'al' => 'Albania',
        'dz' => 'Algeria',
        'ds' => 'American Samoa',
        'ad' => 'Andorra',
        'ao' => 'Angola',
        'ai' => 'Anguilla',
        'aq' => 'Antarctica',
        'ag' => 'Antigua and Barbuda',
        'ar' => 'Argentina',
        'am' => 'Armenia',
        'aw' => 'Aruba',
        'au' => 'Australia',
        'at' => 'Austria',
        'az' => 'Azerbaijan',
        'bs' => 'Bahamas',
        'bh' => 'Bahrain',
        'bd' => 'Bangladesh',
        'bb' => 'Barbados',
        'by' => 'Belarus',
        'be' => 'Belgium',
        'bz' => 'Belize',
        'bj' => 'Benin',
        'bm' => 'Bermuda',
        'bt' => 'Bhutan',
        'bo' => 'Bolivia',
        'ba' => 'Bosnia and Herzegovina',
        'bw' => 'Botswana',
        'br' => 'Brazil',
        'io' => 'British Indian Ocean Territory',
        'bn' => 'Brunei',
        'bg' => 'Bulgaria',
        'bf' => 'Burkina ',
        'bi' => 'Burundi',
        'kh' => 'Cambodia',
        'cm' => 'Cameroon',
        'ca' => 'Canada',
        'cv' => 'Cape Verde',
        'ky' => 'Cayman Islands',
        'cf' => 'Central African Republic',
        'td' => 'Chad',
        'cl' => 'Chile',
        'cn' => 'China',
        'cx' => 'Christmas Island',
        'cc' => 'Cocos Islands',
        'co' => 'Colombia',
        'km' => 'Comoros',
        'ck' => 'Cook Islands',
        'cr' => 'Costa Rica',
        'hr' => 'Croatia',
        'cu' => 'Cuba',
        'cy' => 'Cyprus',
        'cz' => 'Czech Republic',
        'cg' => 'Congo',
        'dk' => 'Denmark',
        'dj' => 'Djibouti',
        'dm' => 'Dominica',
        'tp' => 'East Timor',
        'ec' => 'Ecuador',
        'eg' => 'Egypt',
        'sv' => 'El Salvador',
        'gq' => 'Equatorial Guinea',
        'er' => 'Eritrea',
        'ee' => 'Estonia',
        'et' => 'Ethiopia',
        'fk' => 'Falkland Islands',
        'fo' => 'Faroe ',
        'fj' => 'Fiji',
        'fi' => 'Finland',
        'fr' => 'France',
        'pf' => 'French Polynesia',
        'ga' => 'Gabon',
        'gm' => 'Gambia',
        'ge' => 'Georgia',
        'de' => 'Germany',
        'gh' => 'Ghana',
        'gi' => 'Gibraltar',
        'gr' => 'Greece',
        'gl' => 'Greenland',
        'gd' => 'Grenada',
        'gu' => 'Guam',
        'gt' => 'Guatemala',
        'gk' => 'Guernsey',
        'gn' => 'Guinea',
        'gw' => 'Guinea-',
        'gy' => 'Guyana',
        'ht' => 'Haiti',
        'hn' => 'Honduras',
        'hk' => 'Hong Kong',
        'hu' => 'Hungary',
        'is' => 'Iceland',
        'in' => 'India',
        'id' => 'Indonesia',
        'ir' => 'Iran',
        'iq' => 'Iraq',
        'ie' => 'Ireland',
        'im' => 'Isle of ',
        'il' => 'Israel',
        'it' => 'Italy',
        'ci' => 'Ivory ',
        'jm' => 'Jamaica',
        'jp' => 'Japan',
        'je' => 'Jersey',
        'jo' => 'Jordan',
        'kz' => 'Kazakhstan',
        'ke' => 'Kenya',
        'ki' => 'Kiribati',
        'kp' => 'North Korea',
        'kr' => 'South Korea',
        'xk' => 'Kosovo',
        'kw' => 'Kuwait',
        'kg' => 'Kyrgyzstan',
        'la' => 'Laos',
        'lv' => 'Latvia',
        'lb' => 'Lebanon',
        'ls' => 'Lesotho',
        'lr' => 'Liberia',
        'ly' => 'Libya',
        'li' => 'Liechtenstein',
        'lt' => 'Lithuania',
        'lu' => 'Luxembourg',
        'mo' => 'Macau',
        'mk' => 'Macedonia',
        'mg' => 'Madagascar',
        'mw' => 'Malawi',
        'my' => 'Malaysia',
        'mv' => 'Maldives',
        'ml' => 'Mali',
        'mt' => 'Malta',
        'mh' => 'Marshall Islands',
        'mr' => 'Mauritania',
        'mu' => 'Mauritius',
        'ty' => 'Mayotte',
        'mx' => 'Mexico',
        'fm' => 'Micronesia',
        'md' => 'Moldova, Republic of',
        'mc' => 'Monaco',
        'mn' => 'Mongolia',
        'me' => 'Montenegro',
        'ms' => 'Montserrat',
        'ma' => 'Morocco',
        'mz' => 'Mozambique',
        'mm' => 'Myanmar',
        'na' => 'Namibia',
        'nr' => 'Nauru',
        'np' => 'Nepal',
        'nl' => 'Netherlands',
        'an' => 'Netherlands Antilles',
        'nc' => 'New Caledonia',
        'nz' => 'New Zealand',
        'ni' => 'Nicaragua',
        'ne' => 'Niger',
        'ng' => 'Nigeria',
        'nu' => 'Niue',
        'mp' => 'Northern Mariana Islands',
        'no' => 'Norway',
        'om' => 'Oman',
        'pk' => 'Pakistan',
        'pw' => 'Palau',
        'ps' => 'Palestine',
        'pa' => 'Panama',
        'pg' => 'Papua New Guinea',
        'py' => 'Paraguay',
        'pe' => 'Peru',
        'ph' => 'Philippines',
        'pn' => 'Pitcairn',
        'pl' => 'Poland',
        'pt' => 'Portugal',
        'qa' => 'Qatar',
        're' => 'Reunion',
        'ro' => 'Romania',
        'ru' => 'Russian',
        'rw' => 'Rwanda',
        'kn' => 'Saint Kitts and Nevis',
        'lc' => 'Saint Lucia',
        'vc' => 'Saint Vincent and the Grenadines',
        'ws' => 'Samoa',
        'sm' => 'San Marino',
        'st' => 'Sao Tome and ',
        'sa' => 'Saudi Arabia',
        'sn' => 'Senegal',
        'rs' => 'Serbia',
        'sc' => 'Seychelles',
        'sl' => 'Sierra ',
        'sg' => 'Singapore',
        'sk' => 'Slovakia',
        'si' => 'Slovenia',
        'sb' => 'Solomon Islands',
        'so' => 'Somalia',
        'za' => 'South Africa',
        'es' => 'Spain',
        'lk' => 'Sri Lanka',
        'sd' => 'Sudan',
        'sr' => 'Suriname',
        'sj' => 'Svalbard and Jan Mayen ',
        'sz' => 'Swaziland',
        'se' => 'Sweden',
        'ch' => 'Switzerland',
        'sy' => 'Syria',
        'tw' => 'Taiwan',
        'tj' => 'Tajikistan',
        'tz' => 'Tanzania',
        'th' => 'Thailand',
        'tg' => 'Togo',
        'tk' => 'Tokelau',
        'to' => 'Tonga',
        'tt' => 'Trinidad and Tobago',
        'tn' => 'Tunisia',
        'tr' => 'Turkey',
        'tm' => 'Turkmenistan',
        'tc' => 'Turks and Caicos Islands',
        'tv' => 'Tuvalu',
        'ug' => 'Uganda',
        'ua' => 'Ukraine',
        'ae' => 'United Arab Emirates',
        'gb' => 'United ',
        'us' => 'United States',
        'uy' => 'Uruguay',
        'uz' => 'Uzbekistan',
        'vu' => 'Vanuatu',
        'va' => 'Vatican City State',
        've' => 'Venezuela',
        'vn' => 'Vietnam',
        'vi' => 'Virgin Islands (U.S.)',
        'wf' => 'Wallis and Futuna Islands',
        'eh' => 'Western ',
        'ye' => 'Yemen',
        'zm' => 'Zambia',
        'zw' => 'Zimbabwe'
    ];
    if(is_null($input)){
        return $output;
    }else{
        return $output[$input];
    }
    return $output;
}

/*********************************************
 *		End Ststus Functions
 *********************************************/